Update for 11-27-2018 07-05-36

diff --git a/mkvnmp4 b/mkvnmp4
--- a/mkvnmp4
+++ b/mkvnmp4
@@ -11,6 +11,19 @@
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 PROGRAM_NAME="mkvnmp4"
 
+command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
+    (
+        if [ -x "${DIR}/${PROGRAM_NAME}" ]; then
+            sudo ln -svf "${DIR}/${PROGRAM_NAME}" "/usr/local/bin/${PROGRAM_NAME}"
+            sudo chmod -R 0775 "/usr/local/bin/${PROGRAM_NAME}"
+        else
+            echo "For some reason, linking $PROGRAM_NAME to /usr/local/bin,"
+            echo "failed. My apologies for not being able to figure it out..."
+            exit 1
+        fi
+    )
+}
+
 if [ -f /etc/mkvnmp4.conf ]; then
     . /etc/mkvnmp4.conf
 elif [ -f ~/.mkvnmp4.conf ]; then
